export const types = {
    ADD_PLAYER: "ADD_PLAYER",
    DRAW_CARD: "DRAW_CARD",
    CHAGE_GAMESTATE: "CHAGE_GAMESTATE",
    CHOOSE_DESTINATION: "CHOOSE_DESTINATION",
    NEXT_PLAYER: "NEXT_PLAYER",
    INITIALIZE_STORE: "INITIALIZE_STORE",
    SET_HOVEROBJECT: "SET_HOVEROBJECT",
    BUILD_CONNECTION: "BUILD_CONNECTION",
    UPDATE_STATE: "UPDATE_STATE",
    INITIALIZE_ROOMID: "INITIALIZE_ROOMID",
    RESET_STORE: "RESET_STORE"
};